interval: '5m'
period: 100
instrument: 'BTC-USDT'
risk_strategy: 'allin'
parameter:
  fast_period: 18
  slow_period: 21
  signal_period: 60
  threshold: 0.0004
  exit_period: 10
  proportion: 0.25
  take_profit_level: 0.15
  stop_loss_level: 0.15


